// Package atomkit ...
// Generated by the atom tool.  DO NOT EDIT!
// Source: atom_LocalPosition2
package atomkit

import (
	"github.com/SirMetathyst/atom"

)

// LocalPosition2Key ...
const LocalPosition2Key uint = 1388677675

// LocalPosition2Data ...
type LocalPosition2Data struct {
	X float32
	Y float32	
}

// LocalPosition2Component ...
type LocalPosition2Component struct {
	context atom.Context
	data map[atom.EntityID]LocalPosition2Data
}

// NewLocalPosition2Component ...
func NewLocalPosition2Component() *LocalPosition2Component {
	return &LocalPosition2Component{
		data: make(map[atom.EntityID]LocalPosition2Data),
	}
}

// SetContext ...
func (c *LocalPosition2Component) SetContext(ctx atom.Context) {
	if c.context == nil {
		c.context = ctx
	}
}

func init() {
	x := NewLocalPosition2Component()
	context := atom.Default().RegisterComponent(LocalPosition2Key, x)
	x.SetContext(context)
}

// DeleteEntity ...
func (c *LocalPosition2Component) DeleteEntity(id atom.EntityID) {
	delete(c.data, id)
}

// HasEntity ...
func (c *LocalPosition2Component) HasEntity(id atom.EntityID) bool {
	_, ok := c.data[id]
	return ok
}

// SetLocalPosition2 ...
func (c *LocalPosition2Component) SetLocalPosition2(id atom.EntityID, localposition2 LocalPosition2Data) {
	if c.context.HasEntity(id) {
		if c.HasEntity(id) {
			c.data[id] = localposition2
			c.context.ComponentUpdated(LocalPosition2Key, id)
		} else {
			c.data[id] = localposition2
			c.context.ComponentAdded(LocalPosition2Key, id)
		}
	}
}

// LocalPosition2 ...
func (c *LocalPosition2Component) LocalPosition2(id atom.EntityID) LocalPosition2Data {
	return c.data[id]
}

// DeleteLocalPosition2 ...
func (c *LocalPosition2Component) DeleteLocalPosition2(id atom.EntityID) {
	delete(c.data, id)
	c.context.ComponentDeleted(LocalPosition2Key, id)
}

// SetLocalPosition2X ...
func SetLocalPosition2X(e *atom.EntityManager, id atom.EntityID, localposition2 LocalPosition2Data) {
	v, _ := e.Component(LocalPosition2Key)
	c := v.(*LocalPosition2Component)
	c.SetLocalPosition2(id, localposition2)
}

// SetLocalPosition2 ...
func SetLocalPosition2(id atom.EntityID, localposition2 LocalPosition2Data) {
	SetLocalPosition2X(atom.Default(), id, localposition2)
}

// LocalPosition2X ...
func LocalPosition2X(e *atom.EntityManager, id atom.EntityID) LocalPosition2Data {
	v, _ := e.Component(LocalPosition2Key)
	c := v.(*LocalPosition2Component)
	return c.LocalPosition2(id)
}

// LocalPosition2 ...
func LocalPosition2(id atom.EntityID) LocalPosition2Data {
	return LocalPosition2X(atom.Default(), id)
}

// DeleteLocalPosition2X ...
func DeleteLocalPosition2X(e *atom.EntityManager, id atom.EntityID) {
	v, _ := e.Component(LocalPosition2Key)
	c := v.(*LocalPosition2Component)
	c.DeleteLocalPosition2(id)
}

// DeleteLocalPosition2 ...
func DeleteLocalPosition2(id atom.EntityID) {
	DeleteLocalPosition2X(atom.Default(), id)
}

// HasLocalPosition2X ...
func HasLocalPosition2X(e *atom.EntityManager, id atom.EntityID) bool {
	v, _ := e.Component(LocalPosition2Key)
	return v.HasEntity(id)
}

// HasLocalPosition2 ...
func HasLocalPosition2(id atom.EntityID) bool {
	return HasLocalPosition2X(atom.Default(), id)
}